version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/project/packages/react-scripts/.npmrc
      - run:
          name: Publish package
          command: |
            cd ~/project/packages/react-scripts
            LOCAL_VERSION=`node -p "require('./package.json').version"`
            PUBLISHED_VERSION=`npm view . version`

            if [ "$LOCAL_VERSION" != "$PUBLISHED_VERSION" ]; then
              npm publish
            else
              echo "Skipping publish"
            fi

